### PR TITLE
use of cgo-free sqlite3 driver instead of old one

### PR DESCRIPTION
**Pull request by ashraffouda**

### CODE REVIEW

**Review by muhamadazmy — APPROVED** [review]

**Comment by maxux** [comment]
Do we still use `0-fs` ? Isn't `rfs` the main one used now ?

**Comment by muhamadazmy** [comment]
we use rfs for workloads, basically to mount. But we only use 0-fs for system updates because it's embedded in zos identityd code. Mainly used to open the flist, and download the files directly from the hub without a mount.

**Comment by maxux** [comment]
Why not move to `rfs` as well ? And avoid maintaining two codebases.

**Comment by muhamadazmy** [comment]
As i said, this is "embedded" inside identityd, I would avoid using external binary during an update in case something went wrong. It's better if identityd is self sufficient and doesn't rely on external binaries during it's life time. This way, as long as the executable is intact, we 100% sure the update process will proceed (even with a failed partial update) the process normally goes like this:

- identityd detects a new version
- identityd download itself, make sure that is successful then restart.
- identityd continue updating everything else

This can be as straight forward if we also rely on rfs to update the system. this is why we have to maintain this repo until we rewrite ideneityd in rust, then we can embed the rust implementation instead of the go version

**Pull request merged**
