### PR TITLE
cache: indirection

### LINKED ISSUE #41: flistd: add cache directory indirection to avoid large directory size
@delandtj noticed some large usage of `flist cache` directory, like `7M` directory size, which is not optimal at all for storage.
An easy workaround to fix that is using indirection like `cache/fa/db/abcd00123...` (for hash `fadbabcd00123...`)
An alternative could also be `fa/db/fadbabcd00123` in order to keep filename as full hash.

### PR DESCRIPTION
**Pull request by muhamadazmy**
Fixes #41

### CODE REVIEW

**Review by zaibon — COMMENTED** [review]
Code LGTM.
There should not be any change in go.mod nor go.sum though, since there is no new import or anything.

Also, what is the plan regarding upgrading live node that use the old layout ?
Shouldn't we also handle this somehow ?

**Comment by maxux** [comment]
If nothing is done during migration, things should still works fine but all chunks will be downloaded again and leftover chunks will remains (I guess). This should not break anything but will consume space for nothing.

**Comment by zaibon** [comment]
yeah nothing will break but we are trying to solve the huge inode size issue. If we do not remove what exist in the flat layout, then we do not solve anything. At least not for existing cache

**Comment by maxux** [comment]
I fully agree. Maybe upgrade post-process should take care of this ?
But running process will keep to use old behavior.

Okay, we probably need to handle this here :p

**Comment by muhamadazmy** [comment]
> yeah nothing will break but we are trying to solve the huge inode size issue. If we do not remove what exist in the flat layout, then we do not solve anything. At least not for existing cache

Yeah, i was thinking about this but deleting the already downloaded chunks won't solve the problem (well, at least not immediately) because updating g8ufs will not update the "running" mounts.

So we need probably to only clear the cache on machine reboot because only then we know that the flat cached files are not used by other mounts.

**Review by zaibon — APPROVED** [review]

**Review by maxux — APPROVED** [review]

**Pull request merged**
